server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: pkcs12
    key-store: keystore.p12
    key-store-password: 1234
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://j9b210.p.ssafy.io:8761/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: member-service
          uri: https://j9b210.p.ssafy.io:64412
          predicates:
            - Path=/api/member/**
        - id: board-service
          uri: https://j9b210.p.ssafy.io:64413
          predicates:
            - Path=/api/board/**