server:
  port: 64413

spring:
  application:
    name: board-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://j9b210.p.ssafy.io:8761/eureka/