server:
  port: 64412

spring:
  application:
    name: member-service
  neo4j:
    authentication:
      username: neo4j
      password: { 비밀번호 }
    uri: bolt://{인스턴스 주소}:7687

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka